### ISSUE TITLE
Cannot use flask-ngrok over Colab

### ISSUE THREAD

**Issue by knightowl2704** [gstaff/flask-ngrok#10]
Model loaded. Start serving...

> Exception in thread Thread-5:
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.6/threading.py", line 1182, in run
>     self.function(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/flask_ngrok.py", line 70, in start_ngrok
>     ngrok_address = _run_ngrok()
>   File "/usr/local/lib/python3.6/dist-packages/flask_ngrok.py", line 38, in _run_ngrok
>     tunnel_url = j['tunnels'][0]['public_url']  # Do the parsing of the get
> IndexError: list index out of range

This is the traceback.

**Comment by justolose** [comment]
Hello i'm having the same problem. did you fix it? 
Thanks in advance

**Comment by Santosh-Gupta** [comment]
This issue seems to have returned, even with 0.12.2 version of flask

**Comment by asjgi** [comment]
I have a problem also, It is not working well .................:(

`Mounted at drive
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_ngrok.py", line 70, in start_ngrok
    ngrok_address = _run_ngrok()
  File "/usr/local/lib/python3.6/dist-packages/flask_ngrok.py", line 38, in _run_ngrok
    tunnel_url = j['tunnels'][0]['public_url']  # Do the parsing of the get
IndexError: list index out of range`

**Comment by JozSagh** [comment]
Just quit the current session and re-run:
!pip install flask-ngrok
After reinstalling flask-ngrok the problem is solved.

**Comment by alloc7260** [comment]
Hey, all you can use this [notebook](https://github.com/alloc7260/Project-Snippets/tree/main/run%20a%20web%20application%20(Flask)%20in%20Colab)
insted of this library
